# Generated by Django 5.0.7 on 2024-07-30 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_permisos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Permisos',
            new_name='Permiso',
        ),
    ]
