# Generated by Django 5.0.7 on 2024-07-31 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0005_remove_equipo_usuarios'),
        ('usuarios', '0003_rename_permisos_permiso'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='en_equipos',
            field=models.ManyToManyField(related_name='usuarios_del_equipo', to='equipos.equipo'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='lidera_equipos',
            field=models.ManyToManyField(related_name='lideres', to='equipos.equipo'),
        ),
    ]
