# Generated by Django 5.0.7 on 2024-07-30 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='lider',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipo',
            name='usuarios',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
