# Generated by Django 5.0.7 on 2024-07-30 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0003_remove_equipo_lider_equipo_lider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='lider',
        ),
    ]
