# Generated by Django 5.0.7 on 2024-08-09 14:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0005_remove_equipo_usuarios'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipo',
            options={'ordering': ['created']},
        ),
        migrations.AddField(
            model_name='equipo',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipo',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
