# Generated by Django 5.0.7 on 2024-07-30 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.CharField(max_length=128)),
                ('contraseña', models.CharField(max_length=128)),
                ('estado', models.CharField(choices=[('VENC', 'Vencida'), ('ADQ ', 'Adquirida'), ('VEND ', 'Vendida')], max_length=5)),
                ('estado_pago_proveedor', models.CharField(choices=[('PAG ', 'Pagada'), ('P_PAG', 'Pendiente Pago')], max_length=5)),
                ('fecha_pagada_proveedor', models.CharField(max_length=128)),
                ('estado_pago_vendedor', models.CharField(choices=[('PAG ', 'Pagada'), ('P_PAG', 'Pendiente Pago')], max_length=5)),
                ('fecha_pagada_vendedor', models.CharField(max_length=128)),
                ('fecha_compra', models.CharField(max_length=128)),
                ('fecha_vencimiento', models.CharField(max_length=128)),
                ('vigencia', models.CharField(max_length=128)),
                ('costo_unitario_compra', models.CharField(max_length=128)),
                ('costo_unitario_venta', models.CharField(max_length=128)),
                ('costo_unitario_venta_esp_1', models.CharField(max_length=128)),
                ('costo_unitario_venta_esp_2', models.CharField(max_length=128)),
                ('url_imagen', models.CharField(max_length=128)),
                ('notas', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('tipo_plataforma', models.CharField(max_length=128)),
                ('bodega_actual', models.CharField(max_length=128)),
                ('compras', models.CharField(max_length=128)),
                ('traslados', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPlataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('descripcion', models.TextField()),
                ('url_imagen', models.CharField(max_length=128)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('plataformas', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='plataformas.plataforma')),
            ],
        ),
    ]
