# Generated by Django 5.0.7 on 2025-05-01 00:20

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bodegas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaracteristicasPlataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('descripcion', models.TextField()),
                ('estado_venta', models.CharField(choices=[('TOTAL', 'Total'), ('PARCIAL', 'Parcial')], default='PARCIAL', max_length=7)),
                ('vendida', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='TipoPlataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('descripcion', models.TextField()),
                ('url_imagen', models.CharField(blank=True, max_length=128, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.CharField(max_length=128, unique=True)),
                ('contrasena', models.CharField(max_length=128)),
                ('estado', models.CharField(choices=[('RENO', 'Renovada'), ('ADQ', 'Adquirida'), ('VENC', 'Vencida'), ('VEND', 'Vendida')], default='ADQ', max_length=5)),
                ('fecha_compra', models.DateField(default=django.utils.timezone.now)),
                ('fecha_vencimiento', models.DateField(default=datetime.datetime(2025, 5, 31, 0, 20, 44, 85393, tzinfo=datetime.timezone.utc))),
                ('vigencia', models.SmallIntegerField(default=30)),
                ('precio_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('bodega', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='plataformas_en_la_bodega', to='bodegas.bodega')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plataformas_x_tipo_plataforma', to='plataformas.tipoplataforma')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='CaracteristicasPlataformaValor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=128)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('caracteristica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataformas.caracteristicasplataforma')),
                ('plataforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataformas.plataforma')),
            ],
        ),
        migrations.AddField(
            model_name='caracteristicasplataforma',
            name='tipo_plataforma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataformas.tipoplataforma'),
        ),
    ]
