# Generated by Django 5.0.7 on 2024-07-30 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataformas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plataforma',
            name='costo_unitario_compra',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='plataforma',
            name='costo_unitario_venta',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='plataforma',
            name='costo_unitario_venta_esp_1',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='plataforma',
            name='costo_unitario_venta_esp_2',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='plataforma',
            name='fecha_compra',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='plataforma',
            name='fecha_pagada_proveedor',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='plataforma',
            name='fecha_pagada_vendedor',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='plataforma',
            name='fecha_vencimiento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='plataforma',
            name='vigencia',
            field=models.SmallIntegerField(),
        ),
    ]
