# Generated by Django 5.0.7 on 2025-05-01 00:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataformas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caracteristicasplataforma',
            name='estado_venta',
            field=models.CharField(choices=[('PARCIAL', 'Parcial'), ('TOTAL', 'Total')], default='PARCIAL', max_length=7),
        ),
        migrations.AlterField(
            model_name='plataforma',
            name='estado',
            field=models.CharField(choices=[('VEND', 'Vendida'), ('RENO', 'Renovada'), ('ADQ', 'Adquirida'), ('VENC', 'Vencida')], default='ADQ', max_length=5),
        ),
        migrations.AlterField(
            model_name='plataforma',
            name='fecha_vencimiento',
            field=models.DateField(default=datetime.datetime(2025, 5, 31, 0, 22, 26, 795463, tzinfo=datetime.timezone.utc)),
        ),
    ]
