# Generated by Django 5.0.7 on 2024-07-30 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataformas', '0002_alter_plataforma_costo_unitario_compra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plataforma',
            name='estado',
            field=models.CharField(choices=[('VENC', 'Vencida'), ('VEND ', 'Vendida'), ('ADQ ', 'Adquirida')], max_length=5),
        ),
    ]
