# Generated by Django 5.0.7 on 2025-05-02 19:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataformas', '0002_alter_caracteristicasplataforma_estado_venta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caracteristicasplataforma',
            name='estado_venta',
            field=models.CharField(choices=[('TOTAL', 'Total'), ('PARCIAL', 'Parcial')], default='PARCIAL', max_length=7),
        ),
        migrations.AlterField(
            model_name='plataforma',
            name='estado',
            field=models.CharField(choices=[('VEND', 'Vendida'), ('ADQ', 'Adquirida'), ('RENO', 'Renovada'), ('VENC', 'Vencida')], default='ADQ', max_length=5),
        ),
        migrations.AlterField(
            model_name='plataforma',
            name='fecha_vencimiento',
            field=models.DateField(default=datetime.datetime(2025, 6, 1, 19, 37, 59, 633517, tzinfo=datetime.timezone.utc)),
        ),
    ]
