# Generated by Django 5.0.7 on 2025-05-02 19:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataformas', '0003_alter_caracteristicasplataforma_estado_venta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caracteristicasplataforma',
            name='estado_venta',
        ),
        migrations.AddField(
            model_name='plataforma',
            name='estado_venta_caracteristicas',
            field=models.CharField(choices=[('PARCIAL', 'Parcial'), ('TOTAL', 'Total')], default='PARCIAL', max_length=7),
        ),
        migrations.AlterField(
            model_name='plataforma',
            name='estado',
            field=models.CharField(choices=[('ADQ', 'Adquirida'), ('VENC', 'Vencida'), ('RENO', 'Renovada'), ('VEND', 'Vendida')], default='ADQ', max_length=5),
        ),
        migrations.AlterField(
            model_name='plataforma',
            name='fecha_vencimiento',
            field=models.DateField(default=datetime.datetime(2025, 6, 1, 19, 52, 9, 989818, tzinfo=datetime.timezone.utc)),
        ),
    ]
