# Generated by Django 5.0.7 on 2024-07-30 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataformas', '0004_alter_plataforma_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plataforma',
            name='estado',
            field=models.CharField(choices=[('ADQ ', 'Adquirida'), ('VENC', 'Vencida'), ('VEND ', 'Vendida')], max_length=5),
        ),
    ]
