# Generated by Django 5.0.7 on 2024-07-30 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodegas', '0002_remove_bodega_responsables_bodega_responsables'),
        ('plataformas', '0005_alter_plataforma_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plataforma',
            name='bodega_actual',
        ),
        migrations.AddField(
            model_name='plataforma',
            name='bodega',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='bodegas.bodega'),
            preserve_default=False,
        ),
    ]
