# Generated by Django 5.0.7 on 2024-07-31 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodegas', '0003_remove_bodega_plataformas'),
        ('plataformas', '0006_remove_plataforma_bodega_actual_plataforma_bodega'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plataforma',
            name='tipo_plataforma',
        ),
        migrations.AlterField(
            model_name='plataforma',
            name='bodega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plataformas_en_bodega', to='bodegas.bodega'),
        ),
        migrations.AlterField(
            model_name='plataforma',
            name='compras',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plataformas_en_compra', to='bodegas.bodega'),
        ),
        migrations.AlterField(
            model_name='plataforma',
            name='estado',
            field=models.CharField(choices=[('VEND ', 'Vendida'), ('ADQ ', 'Adquirida'), ('VENC', 'Vencida')], max_length=5),
        ),
        migrations.AlterField(
            model_name='plataforma',
            name='estado_pago_proveedor',
            field=models.CharField(choices=[('PAG ', 'Pagada'), ('P_PAG', 'Pendiente Pago')], max_length=5),
        ),
        migrations.AlterField(
            model_name='plataforma',
            name='estado_pago_vendedor',
            field=models.CharField(choices=[('PAG ', 'Pagada'), ('P_PAG', 'Pendiente Pago')], max_length=5),
        ),
        migrations.AlterField(
            model_name='tipoplataforma',
            name='plataformas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plataformas.plataforma'),
        ),
    ]
