# Generated by Django 5.0.7 on 2024-07-31 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataformas', '0010_alter_plataforma_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipoplataforma',
            name='plataformas',
        ),
        migrations.AddField(
            model_name='plataforma',
            name='tipo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='plataformas_x_tipo_plataforma', to='plataformas.tipoplataforma'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plataforma',
            name='estado',
            field=models.CharField(choices=[('VEND ', 'Vendida'), ('VENC', 'Vencida'), ('ADQ ', 'Adquirida')], max_length=5),
        ),
    ]
