# Generated by Django 5.0.7 on 2024-07-31 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataformas', '0011_remove_tipoplataforma_plataformas_plataforma_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plataforma',
            name='estado_pago_proveedor',
            field=models.CharField(choices=[('PAG ', 'Pagada'), ('P_PAG', 'Pendiente Pago')], max_length=5),
        ),
        migrations.AlterField(
            model_name='plataforma',
            name='estado_pago_vendedor',
            field=models.CharField(choices=[('PAG ', 'Pagada'), ('P_PAG', 'Pendiente Pago')], max_length=5),
        ),
    ]
