# Generated by Django 5.0.7 on 2024-07-31 20:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataformas', '0017_alter_plataforma_costo_unitario_venta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plataforma',
            name='estado_pago_proveedor',
            field=models.CharField(choices=[('PAG ', 'Pagada'), ('P_PAG', 'Pendiente Pago')], default='P_PAG', max_length=5),
        ),
        migrations.AlterField(
            model_name='plataforma',
            name='estado_pago_vendedor',
            field=models.CharField(choices=[('PAG ', 'Pagada'), ('P_PAG', 'Pendiente Pago')], default='P_PAG', max_length=5),
        ),
        migrations.AlterField(
            model_name='plataforma',
            name='fecha_vencimiento',
            field=models.DateField(default=datetime.datetime(2024, 8, 30, 20, 4, 53, 441169, tzinfo=datetime.timezone.utc)),
        ),
    ]
