# Generated by Django 5.0.7 on 2024-07-31 20:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataformas', '0020_alter_plataforma_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plataforma',
            name='estado',
            field=models.CharField(choices=[('VENC', 'Vencida'), ('VEND', 'Vendida'), ('ADQ', 'Adquirida')], default='ADQ', max_length=5),
        ),
        migrations.AlterField(
            model_name='plataforma',
            name='fecha_vencimiento',
            field=models.DateField(default=datetime.datetime(2024, 8, 30, 20, 13, 59, 143842, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tipoplataforma',
            name='url_imagen',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
