# Generated by Django 5.0.7 on 2024-07-31 20:18

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_alter_compra_proveedor'),
        ('plataformas', '0021_alter_plataforma_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plataforma',
            name='compras',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plataformas_en_compra', to='compras.compra'),
        ),
        migrations.AlterField(
            model_name='plataforma',
            name='estado',
            field=models.CharField(choices=[('VEND', 'Vendida'), ('VENC', 'Vencida'), ('ADQ', 'Adquirida')], default='ADQ', max_length=5),
        ),
        migrations.AlterField(
            model_name='plataforma',
            name='estado_pago_proveedor',
            field=models.CharField(choices=[('P_PAG', 'Pendiente Pago'), ('PAG ', 'Pagada')], default='P_PAG', max_length=5),
        ),
        migrations.AlterField(
            model_name='plataforma',
            name='estado_pago_vendedor',
            field=models.CharField(choices=[('P_PAG', 'Pendiente Pago'), ('PAG ', 'Pagada')], default='P_PAG', max_length=5),
        ),
        migrations.AlterField(
            model_name='plataforma',
            name='fecha_vencimiento',
            field=models.DateField(default=datetime.datetime(2024, 8, 30, 20, 18, 2, 900295, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='plataforma',
            name='traslados',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
