# Generated by Django 5.0.7 on 2024-08-02 22:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataformas', '0023_alter_plataforma_correo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plataforma',
            name='traslados',
        ),
        migrations.RemoveField(
            model_name='plataforma',
            name='url_imagen',
        ),
        migrations.AlterField(
            model_name='plataforma',
            name='estado',
            field=models.CharField(choices=[('VENC', 'Vencida'), ('ADQ', 'Adquirida'), ('VEND', 'Vendida')], default='ADQ', max_length=5),
        ),
        migrations.AlterField(
            model_name='plataforma',
            name='fecha_vencimiento',
            field=models.DateField(default=datetime.datetime(2024, 9, 1, 22, 34, 35, 111257, tzinfo=datetime.timezone.utc)),
        ),
    ]
