# Generated by Django 5.0.7 on 2024-08-06 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataformas', '0024_remove_plataforma_traslados_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plataforma',
            old_name='costo_unitario_venta_esp_1',
            new_name='costo_unitario_venta_esp',
        ),
        migrations.RemoveField(
            model_name='plataforma',
            name='costo_unitario_venta_esp_2',
        ),
        migrations.AlterField(
            model_name='plataforma',
            name='estado',
            field=models.CharField(choices=[('RENO', 'Renovada'), ('VEND', 'Vendida'), ('VENC', 'Vencida'), ('ADQ', 'Adquirida')], default='ADQ', max_length=5),
        ),
        migrations.AlterField(
            model_name='plataforma',
            name='estado_pago_proveedor',
            field=models.CharField(choices=[('P_PAG', 'Pendiente Pago'), ('PAG ', 'Pagada')], default='P_PAG', max_length=5),
        ),
        migrations.AlterField(
            model_name='plataforma',
            name='estado_pago_vendedor',
            field=models.CharField(choices=[('P_PAG', 'Pendiente Pago'), ('PAG ', 'Pagada')], default='P_PAG', max_length=5),
        ),
        migrations.AlterField(
            model_name='plataforma',
            name='fecha_vencimiento',
            field=models.DateField(default=datetime.datetime(2024, 9, 5, 17, 0, 18, 346158, tzinfo=datetime.timezone.utc)),
        ),
    ]
