# Generated by Django 5.0.7 on 2024-08-06 18:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataformas', '0025_rename_costo_unitario_venta_esp_1_plataforma_costo_unitario_venta_esp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoplataforma',
            name='precio_default',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='plataforma',
            name='estado',
            field=models.CharField(choices=[('VEND', 'Vendida'), ('RENO', 'Renovada'), ('VENC', 'Vencida'), ('ADQ', 'Adquirida')], default='ADQ', max_length=5),
        ),
        migrations.AlterField(
            model_name='plataforma',
            name='estado_pago_proveedor',
            field=models.CharField(choices=[('PAG ', 'Pagada'), ('P_PAG', 'Pendiente Pago')], default='P_PAG', max_length=5),
        ),
        migrations.AlterField(
            model_name='plataforma',
            name='estado_pago_vendedor',
            field=models.CharField(choices=[('PAG ', 'Pagada'), ('P_PAG', 'Pendiente Pago')], default='P_PAG', max_length=5),
        ),
        migrations.AlterField(
            model_name='plataforma',
            name='fecha_vencimiento',
            field=models.DateField(default=datetime.datetime(2024, 9, 5, 18, 6, 1, 585119, tzinfo=datetime.timezone.utc)),
        ),
    ]
