# Generated by Django 5.0.7 on 2024-08-06 18:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataformas', '0026_tipoplataforma_precio_default_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plataforma',
            old_name='costo_unitario_compra',
            new_name='precio_compra',
        ),
        migrations.RenameField(
            model_name='plataforma',
            old_name='costo_unitario_venta',
            new_name='precio_venta',
        ),
        migrations.RenameField(
            model_name='plataforma',
            old_name='costo_unitario_venta_esp',
            new_name='precio_venta_2',
        ),
        migrations.AlterField(
            model_name='plataforma',
            name='estado',
            field=models.CharField(choices=[('RENO', 'Renovada'), ('ADQ', 'Adquirida'), ('VEND', 'Vendida'), ('VENC', 'Vencida')], default='ADQ', max_length=5),
        ),
        migrations.AlterField(
            model_name='plataforma',
            name='estado_pago_proveedor',
            field=models.CharField(choices=[('P_PAG', 'Pendiente Pago'), ('PAG ', 'Pagada')], default='P_PAG', max_length=5),
        ),
        migrations.AlterField(
            model_name='plataforma',
            name='estado_pago_vendedor',
            field=models.CharField(choices=[('P_PAG', 'Pendiente Pago'), ('PAG ', 'Pagada')], default='P_PAG', max_length=5),
        ),
        migrations.AlterField(
            model_name='plataforma',
            name='fecha_vencimiento',
            field=models.DateField(default=datetime.datetime(2024, 9, 5, 18, 7, 52, 229375, tzinfo=datetime.timezone.utc)),
        ),
    ]
