# Generated by Django 5.0.7 on 2024-08-09 14:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataformas', '0030_alter_plataforma_estado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plataforma',
            options={'ordering': ['created']},
        ),
        migrations.AlterModelOptions(
            name='tipoplataforma',
            options={'ordering': ['created']},
        ),
        migrations.AlterField(
            model_name='plataforma',
            name='estado',
            field=models.CharField(choices=[('RENO', 'Renovada'), ('ADQ', 'Adquirida'), ('VENC', 'Vencida'), ('VEND', 'Vendida')], default='ADQ', max_length=5),
        ),
        migrations.AlterField(
            model_name='plataforma',
            name='fecha_vencimiento',
            field=models.DateField(default=datetime.datetime(2024, 9, 8, 14, 45, 6, 650726, tzinfo=datetime.timezone.utc)),
        ),
    ]
