# Generated by Django 5.0.7 on 2024-08-12 19:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataformas', '0033_alter_plataforma_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plataforma',
            name='estado',
            field=models.CharField(choices=[('ADQ', 'Adquirida'), ('RENO', 'Renovada'), ('VEND', 'Vendida'), ('VENC', 'Vencida')], default='ADQ', max_length=5),
        ),
        migrations.AlterField(
            model_name='plataforma',
            name='fecha_vencimiento',
            field=models.DateField(default=datetime.datetime(2024, 9, 11, 19, 39, 19, 16223, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='plataforma',
            name='precio_compra',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
