# Generated by Django 5.0.7 on 2024-08-12 21:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataformas', '0034_alter_plataforma_estado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plataforma',
            old_name='compras',
            new_name='compra',
        ),
        migrations.AlterField(
            model_name='plataforma',
            name='estado',
            field=models.CharField(choices=[('VENC', 'Vencida'), ('VEND', 'Vendida'), ('RENO', 'Renovada'), ('ADQ', 'Adquirida')], default='ADQ', max_length=5),
        ),
        migrations.AlterField(
            model_name='plataforma',
            name='estado_pago_proveedor',
            field=models.CharField(choices=[('PAG ', 'Pagada'), ('P_PAG', 'Pendiente Pago')], default='P_PAG', max_length=5),
        ),
        migrations.AlterField(
            model_name='plataforma',
            name='estado_pago_vendedor',
            field=models.CharField(choices=[('PAG ', 'Pagada'), ('P_PAG', 'Pendiente Pago')], default='P_PAG', max_length=5),
        ),
        migrations.AlterField(
            model_name='plataforma',
            name='fecha_vencimiento',
            field=models.DateField(default=datetime.datetime(2024, 9, 11, 21, 11, 18, 290432, tzinfo=datetime.timezone.utc)),
        ),
    ]
