# Generated by Django 5.0.7 on 2025-02-12 22:34

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodegas', '0004_alter_bodega_options'),
        ('compras', '0006_alter_compra_notas'),
        ('plataformas', '0036_rename_contraseña_plataforma_contrasena_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plataforma',
            name='bodega',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='plataformas_en_la_bodega', to='bodegas.bodega'),
        ),
        migrations.AlterField(
            model_name='plataforma',
            name='compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plataformas_en_la_compra', to='compras.compra'),
        ),
        migrations.AlterField(
            model_name='plataforma',
            name='estado',
            field=models.CharField(choices=[('ADQ', 'Adquirida'), ('RENO', 'Renovada'), ('VEND', 'Vendida'), ('VENC', 'Vencida')], default='ADQ', max_length=5),
        ),
        migrations.AlterField(
            model_name='plataforma',
            name='fecha_vencimiento',
            field=models.DateField(default=datetime.datetime(2025, 3, 14, 22, 34, 7, 196685, tzinfo=datetime.timezone.utc)),
        ),
    ]
