# Generated by Django 5.0.7 on 2025-02-13 22:48

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodegas', '0004_alter_bodega_options'),
        ('compras', '0006_alter_compra_notas'),
        ('plataformas', '0037_alter_plataforma_bodega_alter_plataforma_compra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plataforma',
            name='bodega',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='plataformas_en_la_bodega', to='bodegas.bodega'),
        ),
        migrations.AlterField(
            model_name='plataforma',
            name='compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plataformas_en_la_compra', to='compras.compra'),
        ),
        migrations.AlterField(
            model_name='plataforma',
            name='estado',
            field=models.CharField(choices=[('RENO', 'Renovada'), ('VEND', 'Vendida'), ('ADQ', 'Adquirida'), ('VENC', 'Vencida')], default='ADQ', max_length=5),
        ),
        migrations.AlterField(
            model_name='plataforma',
            name='fecha_vencimiento',
            field=models.DateField(default=datetime.datetime(2025, 3, 15, 22, 48, 26, 619106, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='plataforma',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plataformas_x_tipo_plataforma', to='plataformas.tipoplataforma'),
        ),
        migrations.CreateModel(
            name='CaracteristicasPlataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('descripcion', models.TextField()),
                ('precio_referencia', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('plataforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataformas.plataforma')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
