# Generated by Django 5.0.7 on 2025-02-13 22:52

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataformas', '0038_alter_plataforma_bodega_alter_plataforma_compra_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caracteristicasplataforma',
            name='plataforma',
        ),
        migrations.AddField(
            model_name='caracteristicasplataforma',
            name='tipo_plataforma',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='plataformas.tipoplataforma'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plataforma',
            name='estado',
            field=models.CharField(choices=[('VEND', 'Vendida'), ('RENO', 'Renovada'), ('VENC', 'Vencida'), ('ADQ', 'Adquirida')], default='ADQ', max_length=5),
        ),
        migrations.AlterField(
            model_name='plataforma',
            name='fecha_vencimiento',
            field=models.DateField(default=datetime.datetime(2025, 3, 15, 22, 50, 11, 705939, tzinfo=datetime.timezone.utc)),
        ),
    ]
