# Generated by Django 5.0.7 on 2025-05-01 00:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bodegas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bodega',
            name='responsables',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
