# Generated by Django 5.0.7 on 2024-07-31 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bodegas', '0002_remove_bodega_responsables_bodega_responsables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bodega',
            name='plataformas',
        ),
    ]
