# Generated by Django 5.0.7 on 2024-08-09 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bodegas', '0003_remove_bodega_plataformas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bodega',
            options={'ordering': ['created']},
        ),
    ]
