# Generated by Django 5.0.7 on 2025-05-02 19:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodegas', '0003_bodega_activa_bodega_principal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodega',
            name='responsables',
            field=models.ManyToManyField(related_name='responsable_de_bodegas', to=settings.AUTH_USER_MODEL),
        ),
    ]
