# Generated by Django 5.0.7 on 2024-07-30 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Traslado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('notas', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('responsable', models.CharField(max_length=128)),
                ('plataforma', models.CharField(max_length=128)),
                ('bodega_origen', models.CharField(max_length=128)),
                ('bodega_destino', models.CharField(max_length=128)),
            ],
        ),
    ]
