# Generated by Django 5.0.7 on 2025-04-29 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bodegas', '0001_initial'),
        ('plataformas', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traslado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('notas', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('bodega_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traslados_hacia', to='bodegas.bodega')),
                ('bodega_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traslados_desde', to='bodegas.bodega')),
                ('plataforma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traslados_realizados', to='plataformas.plataforma')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsable_de_traslados', to='usuarios.usuario')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
