# Generated by Django 5.0.7 on 2024-08-02 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodegas', '0003_remove_bodega_plataformas'),
        ('plataformas', '0023_alter_plataforma_correo_and_more'),
        ('traslados', '0001_initial'),
        ('usuarios', '0004_usuario_en_equipos_usuario_lidera_equipos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traslado',
            name='bodega_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traslados_hacia', to='bodegas.bodega'),
        ),
        migrations.AlterField(
            model_name='traslado',
            name='bodega_origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traslados_desde', to='bodegas.bodega'),
        ),
        migrations.AlterField(
            model_name='traslado',
            name='plataforma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traslados_realizados', to='plataformas.plataforma'),
        ),
        migrations.AlterField(
            model_name='traslado',
            name='responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsable_de_traslados', to='usuarios.usuario'),
        ),
    ]
