# Generated by Django 5.0.7 on 2024-08-02 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traslados', '0002_alter_traslado_bodega_destino_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traslado',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
    ]
