# Generated by Django 5.0.7 on 2024-08-09 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traslados', '0003_alter_traslado_notas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='traslado',
            options={'ordering': ['created']},
        ),
    ]
