# Generated by Django 5.0.7 on 2025-04-29 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=128)),
                ('apellidos', models.CharField(max_length=128)),
                ('email', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('web', models.CharField(blank=True, max_length=256, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=128, null=True)),
                ('url_imagen', models.CharField(blank=True, max_length=256, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Proveedores',
                'ordering': ['created'],
            },
        ),
    ]
