# Generated by Django 5.0.7 on 2024-07-31 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
        ('usuarios', '0003_rename_permisos_permiso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='compras',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='usuario',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario'),
            preserve_default=False,
        ),
    ]
