# Generated by Django 5.0.7 on 2024-07-31 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_remove_proveedor_compras_proveedor_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='url_imagen',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='web',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
