# Generated by Django 5.0.7 on 2024-08-09 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0003_remove_proveedor_usuario_alter_proveedor_activo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedor',
            options={'ordering': ['created']},
        ),
    ]
