# Generated by Django 5.0.7 on 2025-05-01 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plataformas', '0001_initial'),
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('notas', models.TextField(blank=True, null=True)),
                ('estado_pago', models.CharField(choices=[('P_PAG', 'Pendiente Pago'), ('PAG', 'Pagada')], default='P_PAG', max_length=5)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras_del_proveedor', to='proveedores.proveedor')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Compra_detalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('Compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras_detalle', to='compras.compra')),
                ('Plataforma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras_detalle', to='plataformas.plataforma')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
