# Generated by Django 5.0.7 on 2024-07-31 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_compra_fecha_compra_notas'),
        ('usuarios', '0003_rename_permisos_permiso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='plataformas',
        ),
        migrations.AlterField(
            model_name='compra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.usuario'),
        ),
    ]
