# Generated by Django 5.0.7 on 2024-07-31 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_remove_compra_plataformas_alter_compra_proveedor'),
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras_del_proveedor', to='proveedores.proveedor'),
        ),
    ]
