# Generated by Django 5.0.7 on 2024-08-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_alter_compra_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
    ]
