# Generated by Django 5.0.7 on 2025-04-29 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('notas', models.TextField()),
                ('estado_pago', models.CharField(choices=[('P_PAG', 'Pendiente Pago'), ('PAG', 'Pagada')], default='P_PAG', max_length=5)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas_del_cliente', to='clientes.cliente')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
