# Generated by Django 5.0.7 on 2024-08-09 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venta',
            options={'ordering': ['created']},
        ),
    ]
