# Generated by Django 5.0.7 on 2025-05-02 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_alter_venta_estado_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='estado_pago',
            field=models.CharField(choices=[('P_PAG', 'Pendiente Pago'), ('PAG', 'Pagada')], default='P_PAG', max_length=5),
        ),
    ]
